spring.application.name=currency-converter
server.port=8587

spring.boot.admin.client.url=http://localhost:9090
spring.boot.admin.client.instance.management-base-url=http://localhost:6083

spring.threads.virtual.enabled=true

management.server.port=6083
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always